Problem Statement: Consider the ratings dataset below, containing the data on: UserID, MovieID, Rating and Timestamp. Each line of this file represents one rating of one movie by one user, and has the following format: UserID::MovieID::Rating::Timestamp
Ratings are made on a 5 star scale with half star increments.
UserID: represents ID of the user
MovieID: represents ID of the movie
Timestamp: represents seconds from midnight Coordinated Universal Time (UTC) of January 1, 1970.
Objective: Predicta User-movie recommendation model.

In [53]:
import pandas as pd
import numpy as np
r_cols = ['userId', 'movieId', 'rating', 'unix_timestamp']
df=pd.read_csv("C:/Users/sharv/Documents/Post Graduate Program In Data Science-PurdueSimpliLearn/Course3-Machine Learning/Demo Datasets/Recommend.csv",names=r_cols)
print(df.head())
print(df.shape)

   userId  movieId  rating  unix_timestamp
0     196      242       3       881250949
1     186      302       3       891717742
2      22      377       1       878887116
3     244       51       2       880606923
4     166      346       1       886397596
(100000, 4)


In [54]:
from sklearn.model_selection import train_test_split
n_users=df.userId.unique().shape[0] #no. of users
n_movies=df.movieId.unique().shape[0] #no. of movies
train_data,test_data=train_test_split(df, test_size=0.25)

In [55]:
train_data_matrix=np.zeros((n_users,n_movies)) # creating zero matrix
# we will populate train and test matrix with rating such that the userId index - moviId index = the given rating.
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
train_data_matrix # he had some movie ratings on training set but i m getting error. He did the same for testing set.

array([[0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [41]:
#r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
#ratings_train = pd.read_csv('C:/Users\sharv/Documents/Post Graduate Program In Data Science-PurdueSimpliLearn/Course3-Machine Learning/Day 10/ua.base', sep='\t', names=r_cols, encoding='latin-1')
#ratings_test = pd.read_csv('C:/Users\sharv/Documents/Post Graduate Program In Data Science-PurdueSimpliLearn/Course3-Machine Learning/Day 10/ua.test', sep='\t', names=r_cols, encoding='latin-1')
#ratings_train.shape, ratings_test.shape

In [42]:
#n_users = ratings_train.user_id.unique().shape[0]
#n_items = ratings_train.movie_id.unique().shape[0]

In [43]:
#data_matrix = np.zeros((n_users, n_items))
#for line in ratings_train.itertuples():
#    data_matrix[line[1]-1, line[2]-1] = line[3]

In [56]:
test_data_matrix=np.zeros((n_users,n_movies)) 
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1]=line[3]
test_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
# creating cosine similarity matrices for users and movies
# cosine similarity is measure of similarity between 2 non-zero vectors of interproduct space that measures the cosine of 
# the angle between them. cosine is zero degrees is 1 and it is less than 1 for any angle in the interval 0 Pi radians.
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix,metric='cosine')
movie_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')

In [58]:
# now we will go with predictions based on the fact that user movie collaborative filterings difference from mean rating
# is a better indicator than absolute rating.
# Calculate user predictions such that user prediction is sum of mean user rating and the dot product of user similarity
# and ratings difference, divided by absolute value of user similarity.
# The matrix we recceived as output describes how those unrated movies will be rated by users based on their prior rating
# styles.
mean_user_rating=train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff=(train_data_matrix-mean_user_rating)
user_pred=mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.65606866,  0.5716249 ,  0.48167515, ...,  0.30180283,
         0.30185545,  0.29936122],
       [ 1.34544099,  0.27040643,  0.13527824, ..., -0.06407648,
        -0.06266188, -0.0660003 ],
       [ 1.35831975,  0.22286295,  0.10022067, ..., -0.10437244,
        -0.10280243, -0.10604021],
       ...,
       [ 1.23445117,  0.19883947,  0.06968692, ..., -0.12173353,
        -0.12075019, -0.12398496],
       [ 1.40520874,  0.29368024,  0.18690266, ..., -0.01239082,
        -0.0115582 , -0.01452064],
       [ 1.45567788,  0.36713286,  0.28756111, ...,  0.11084445,
         0.11078781,  0.10832633]])

 recap
1> import libraries and the dataset
2> identify total number of users and movies
3> split the data into training and testing sets
4> populate the train test metrices with random ratings
5> create cosine similarity metrices for users and movies
6> perform predictions

Movie- Movie Recommendation
DESCRIPTION

Consider the ratings dataset below containing data on UserID, MovieID, Rating, and Timestamp. Each line of this file represents one rating of one movie by one user and has the following format: UserID::MovieID::Rating::Timestamp Ratings are made on a 5 star scale with half star increments. UserID: represents the ID of the user MovieID: represents the ID of the movie Timestamp: represents seconds from midnight Coordinated Universal Time (UTC) of January 1, 1970.
Objective: Predict a movie-movie recommendation model.

In [59]:
# Step 01

df = pd.read_csv('C:/Users/sharv/Documents/Post Graduate Program In Data Science-PurdueSimpliLearn/Course3-Machine Learning/Demo Datasets/Recommend.csv',names=['user_id', 'movie_id', 'rating', 'timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [60]:
# Step 02
# Create a train test split of 75/25 by declaring number of users and movies

n_users= df.user_id.unique().shape[0] 
n_movies= df.movie_id.unique().shape[0]
train_data, test_data= train_test_split(df, test_size=0.25)

In [61]:
# Step 03
# Populate the train matrix (user_idx movie_id) with ratings such that [user_idindex, movie_idindex] = given rating

train_data_matrix= np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_idindex, movie_idindex] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
train_data_matrix

array([[5., 3., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [62]:
# Step 04
# Populate the test matrix (user_idx movie_id) with ratings such that [user_idindex, movie_idindex] = given rating

test_data_matrix= np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_idindex, movie_idindex] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [64]:
# Step 05
# Create cosine similarity matrices for movies and predict a movie-movie recommendation model

movie_similarity= pairwise_distances(train_data_matrix.T, metric='cosine')
movie_pred= train_data_matrix.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

array([[0.38509289, 0.40289305, 0.43104189, ..., 0.46967671, 0.45959807,
        0.45575547],
       [0.10114764, 0.11768173, 0.11276026, ..., 0.11817935, 0.11976559,
        0.12009295],
       [0.06222649, 0.06492201, 0.0635383 , ..., 0.05967131, 0.06410581,
        0.06436895],
       ...,
       [0.0309901 , 0.04012331, 0.03809935, ..., 0.04450092, 0.04401544,
        0.0436033 ],
       [0.131557  , 0.13904667, 0.14903204, ..., 0.15286508, 0.15129057,
        0.15394827],
       [0.20153359, 0.19924025, 0.22113181, ..., 0.2524793 , 0.24325265,
        0.24401651]])