In [ ]:
# Problem Statement: Motion Studios is the largest radio production house in Europe. Its total revenue is $ 1B+. The company
# has launched a new reality show "The Star RJ." The show is about finding a new radio jockey who will be the star presenter
# on upcoming shows.
# In the first round, participants have to upload their voice clip online. The clip will be evaluated by experts for 
# selection to the next round. There is a separate team in the first round for evaluation of male and female voice.
# Response to the show is unprecedented, and company is flooded with voice clips.
# You “as an ML” expert have to classify the voice as either male or female so that the first level of filtration is quicker.
 # Objective: Optimizeselection process.

In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv("C:/Users/sharv/Documents/Post Graduate Program In Data Science-PurdueSimpliLearn/Course3-Machine Learning/Demo Datasets for pdf/Lesson 6/voice-classification.csv")
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   obje

In [49]:
df.describe()
# dataset has 4000 entries

meanfreq           sd       median          Q25          Q75  \
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000   
mean      0.180907     0.057126     0.185621     0.140456     0.224765   
std       0.029918     0.016652     0.036360     0.048680     0.023639   
min       0.039363     0.018363     0.010975     0.000229     0.042946   
25%       0.163662     0.041954     0.169593     0.111087     0.208747   
50%       0.184838     0.059155     0.190032     0.140286     0.225684   
75%       0.199146     0.067020     0.210618     0.175939     0.243660   
max       0.251124     0.115273     0.261224     0.247347     0.273469   

               IQR         skew         kurt       sp.ent          sfm  \
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000   
mean      0.084309     3.140168    36.568461     0.895127     0.408216   
std       0.042783     4.240529   134.928661     0.044980     0.177521   
min       0.014558     0.141735     2.068455     0.738651     0.036876   
25%       0.042560     1.649569     5.669547     0.861811     0.258041   
50%       0.094280     2.197101     8.318463     0.901767     0.396335   
75%       0.114175     2.931694    13.648905     0.928713     0.533676   
max       0.252225    34.725453  1309.612887     0.981997     0.842936   

              mode     centroid      meanfun       minfun       maxfun  \
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000   
mean      0.165282     0.180907     0.142807     0.036802     0.258842   
std       0.077203     0.029918     0.032304     0.019220     0.030077   
min       0.000000     0.039363     0.055565     0.009775     0.103093   
25%       0.118016     0.163662     0.116998     0.018223     0.253968   
50%       0.186599     0.184838     0.140519     0.046110     0.271186   
75%       0.221104     0.199146     0.169581     0.047904     0.277457   
max       0.280000     0.251124     0.237636     0.204082     0.279114   

           meandom       mindom       maxdom      dfrange      modindx  
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000  
mean      0.829211     0.052647     5.047277     4.994630     0.173752  
std       0.525205     0.063299     3.521157     3.520039     0.119454  
min       0.007812     0.004883     0.007812     0.000000     0.000000  
25%       0.419828     0.007812     2.070312     2.044922     0.099766  
50%       0.765795     0.023438     4.992188     4.945312     0.139357  
75%       1.177166     0.070312     7.007812     6.992188     0.209183  
max       2.957682     0.458984    21.867188    21.843750     0.932374

In [50]:
df.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [51]:
print("shape of data:",df.shape)
print("total number of labels: {}".format(df.shape[0]))
print("Number of male: {}".format(df[df.label=="male"].shape[0]))
print("Number of female: {}".format(df[df.label=="female"].shape[0]))

shape of data: (3168, 21)
total number of labels: 3168
Number of male: 1584
Number of female: 1584


In [52]:
# extract target variables within X
X =df.iloc[:,:-1]
print(df.shape)
print(X.shape)

(3168, 21)
(3168, 20)


In [53]:
# since we solving classification problem, labels must b converted to numerical form
# male will get encoded as 1 and female as 0
from sklearn.preprocessing import LabelEncoder
y=df.iloc[:,-1]
gender_encoder=LabelEncoder()
y=gender_encoder.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [54]:
# now to make model efficient we will have to scale the training data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.30,random_state=100)

In [56]:
# now let's train SVM classifier
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
# fitting model on the training datasets
svc_model=SVC()
svc_model.fit(X_train,y_train)
# perform predictions on the testing sets
y_pred=svc_model.predict(X_test)
print("Accuracy score:", metrics.accuracy_score(y_test,y_pred))

Accuracy score: 0.9737118822292324


In [57]:
print(confusion_matrix(y_test,y_pred))

[[458  13]
 [ 12 468]]


In [58]:
# to optimize the result we will use GridSearch
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[1,0.1,0.01,0.001]}
grid=GridSearchCV(SVC(),param_grid,refit=True,verbose=2) 
# parameter refit refits an estimator using the best found parameter on the whole dataset 
# fitting grid search model on the training sets
grid.fit(X_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.1s
[CV] C=0.1, gamma=1 ..................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ................................... C=0.1, gamma=1, total=   0.1s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.1s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.1s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.1s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.1s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .

[CV] ................................... C=100, gamma=1, total=   0.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   0.1s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.0s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.0s
[CV] C=100, gamma=0.1 ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    4.8s finished


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

In [59]:
# now take that grid model and create some predictions using the test set
grid_predictions=grid.predict(X_test)
print("Accuracy score:", metrics.accuracy_score(y_test,grid_predictions))

Accuracy score: 0.9747634069400631


In [60]:
print(confusion_matrix(y_test,grid_predictions))

[[459  12]
 [ 12 468]]


In [61]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       471
           1       0.97      0.97      0.97       480

    accuracy                           0.97       951
   macro avg       0.97      0.97      0.97       951
weighted avg       0.97      0.97      0.97       951



In [ ]:
# recap
#1> import libraries and the dataset
#2> check for missing values
#3> check the distribution of the dataset
#4> preprocess the dataset using label encoders
#5> fit SVM classifier on the transformed data
#6> print the accuracy, confusion matrix and classification report
#7> use the grid search to optimize the results further
#8> print the accuracy, confusion matrix and classification report of the optimized model.

In [ ]:
# Problem Statement: Load the data from “college.csv” that has attributes collected about private and public colleges for a 
# particular year. Predict the private/public status of the colleges from other attributes.
# Use LabelEncoderto encode the target variable to numerical form. Split the data such that 20% of the data is set aside for
# testing. Fit a linear svmfrom scikitlearn and observe the accuracy. [Hint: Use Linear SVC]
# Preprocessthe data using StandardScalarand fit the same model again. Observe the change in accuracy.
# Use scikitlearn’sgridsearchto select the best hyperparameter for a nonlinear SVM. Identify the model with best score and 
# its parameters. [Hint: Refer to model_selectionmodule of Scikitlearn]
# Objective: Employ SVM from scikitlearn for binary classification and measure the impact of preprocessingdata and hyper
# parameter search using grid search.

In [147]:
import pandas as pd
df = pd.read_csv("C:/Users/sharv/Documents/Post Graduate Program In Data Science-PurdueSimpliLearn/Course3-Machine Learning/Demo Datasets for pdf/College.csv")
df.columns


Index(['Unnamed: 0', 'Private', 'Apps', 'Accept', 'Enroll', 'Top10perc',
       'Top25perc', 'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board',
       'Books', 'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni',
       'Expend', 'Grad.Rate'],
      dtype='object')

In [148]:
df.head()

Unnamed: 0 Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

In [149]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
X, y = df.iloc[:,1:].values, df.iloc[:,0].values
labelencoder_X = LabelEncoder()
print(X.shape)
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])
print(X)
print(X.shape)
print(y)
#X = X.reshape(len(X[:, 0]), 7)
print(X.shape)

onehotencoder = OneHotEncoder()

categorical_features = [0]
# Send only the first column to onehotencoder
X_oneHotEncoded = onehotencoder.fit_transform(X[:, categorical_features]).toarray()

# Combine the two arrays back together
X_final = np.hstack((X_oneHotEncoded, X[:,1:]))

(777, 18)
[[1 352 1232 ... 12 7041 60]
 [1 414 1924 ... 16 10527 56]
 [1 314 1097 ... 30 8735 54]
 ...
 [1 404 1915 ... 20 8323 49]
 [1 668 2453 ... 49 40386 99]
 [1 481 1855 ... 28 4509 99]]
(777, 18)
['Abilene Christian University' 'Adelphi University' 'Adrian College'
 'Agnes Scott College' 'Alaska Pacific University' 'Albertson College'
 'Albertus Magnus College' 'Albion College' 'Albright College'
 'Alderson-Broaddus College' 'Alfred University' 'Allegheny College'
 'Allentown Coll. of St. Francis de Sales' 'Alma College'
 'Alverno College' 'American International College' 'Amherst College'
 'Anderson University' 'Andrews University' 'Angelo State University'
 'Antioch University' 'Appalachian State University' 'Aquinas College'
 'Arizona State University Main campus' 'Arkansas College (Lyon College)'
 'Arkansas Tech University' 'Assumption College'
 'Auburn University-Main Campus' 'Augsburg College' 'Augustana College IL'
 'Augustana College' 'Austin College' 'Averett College' 'B

In [150]:
X_final.shape

(777, 19)

In [151]:
# label encoding
from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import LabelEncoder
X, y = X_final[:,1:], X_final[:,0]
# male -> 1
# female -> 0
target_encoder= LabelEncoder()
y = target_encoder.fit_transform(y)
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)
# it should be (621,17)

(621, 18)


In [152]:
X_train

array([[1.0, 72, 402, ..., 48, 18953, 61],
       [1.0, 106, 454, ..., 31, 9552, 53],
       [1.0, 228, 750, ..., 24, 11291, 70],
       ...,
       [1.0, 613, 3813, ..., 36, 13675, 93],
       [1.0, 127, 494, ..., 31, 7949, 39],
       [1.0, 446, 1402, ..., 33, 12580, 91]], dtype=object)

In [153]:
# fit the linear SVC classifier
from sklearn.svm import LinearSVC,SVC
classifier = LinearSVC()
classifier.fit(X_train,y_train)
print(classifier.get_params())
y_predict= classifier.predict(X_test)
classifier.score(X_test,y_test)

# it should be 0.83333

{'C': 1.0, 'class_weight': None, 'dual': True, 'fit_intercept': True, 'intercept_scaling': 1, 'loss': 'squared_hinge', 'max_iter': 1000, 'multi_class': 'ovr', 'penalty': 'l2', 'random_state': None, 'tol': 0.0001, 'verbose': 0}


0.9294871794871795

In [154]:
# Obtain Performance Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_predict,y_test))
# it should be [[39   26]
#                [0  91]]

[[116  10]
 [  1  29]]


In [155]:
# Fit the SVC Classifier
classifier = SVC()
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)
# it should be 0.75

0.9294871794871795

In [156]:
# Preprocess the Data

from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X, y = X_final[:, 1:], X_final[:, 0]
X = scaler.fit_transform(X)
target_encoder= LabelEncoder()
y = target_encoder.fit_transform(y)
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)
# it should be (621, 17)

(621, 18)


In [157]:
# Refitting the SVC Model

classifier = SVC()
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)
# it should be 0.94

0.9935897435897436

In [158]:
# Fitting Grid Search

import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
C_range= np.logspace(-2, 10, 13)
gamma_range= np.logspace(-9, 3, 13)
param_grid= dict( gamma=gamma_range,C=C_range)
grid = GridSearchCV(SVC(), param_grid=param_grid)
grid.fit(X_train, y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10]),
                         'gamma': array([1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02,
       1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])})

In [159]:
# Getting the Best Hyperparameter

print("The best parameters are %s with a score of %0.2f"
% (grid.best_params_, grid.best_score_))

# it should be {'C': 10000000.0, 'gamma': 9.99e-07} with a score of 0.94

The best parameters are {'C': 1.0, 'gamma': 0.01} with a score of 1.00
