In [1]:
# In this demo will learn how to persist the model for future use 
from sklearn.datasets import load_iris
# use iris dataset object to create an instance of the dataset
iris_dataset = load_iris()

In [2]:
# view feature names of the dataset
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
# view target of the dataset
print(iris_dataset.target_names)
iris_dataset.target

['setosa' 'versicolor' 'virginica']


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
# define features and target objects
X_features = iris_dataset.data
Y_target=iris_dataset.target

In [19]:
# # create object with new values for prediction
X_new=[[3,5,4,1],[5,3,4,2]]

In [20]:
# use the logistic regression estimator(trying to predict the outcome using logistic regression model)
# first import logistic regression class and instantiate it
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=10000)

In [22]:
# fit data into logistic regression estimator
logreg.fit(X_features,Y_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
# predict the outcome using Logistic regression estimator
logreg.predict(X_new) #My output is wrong. It should be array([0,2])

array([0, 1])

In [24]:
# It's now time to predict the outcome for new observation which we created as we can see it matches the target labels.
# 0 and 2 from 0,1&2. This means that model is working as expected. so Let's see how u can save it so u won't have to 
# train it everytime u need it. To do this import pickle, use the dumps method and pass the estimator to it to persist the model.
# import library for model persistence
import pickle as pk1

In [25]:
# use dumps method to persist the model
persist_model = pk1.dumps(logreg)
persist_model

b'\x80\x03csklearn.linear_model._logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x05\x00\x00\x00lbfgsq\rX\x08\x00\x00\x00max_iterq\x0eM\x10\'X\x0b\x00\x00\x00multi_classq\x0fX\x04\x00\x00\x00autoq\x10X\x07\x00\x00\x00verboseq\x11K\x00X\n\x00\x00\x00warm_startq\x12\x89X\x06\x00\x00\x00n_jobsq\x13NX\x08\x00\x00\x00l1_ratioq\x14NX\x08\x00\x00\x00classes_q\x15cnumpy.core.multiarray\n_reconstruct\nq\x16cnumpy\nndarray\nq\x17K\x00\x85q\x18C\x01bq\x19\x87q\x1aRq\x1b(K\x01K\x03\x85q\x1ccnumpy\ndtype\nq\x1dX\x02\x00\x00\x00i4q\x1eK\x00K\x01\x87q\x1fRq (K\x03X\x01\x00\x00\x00<q!NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq"b\x89C\x0c\x00\x0

In [26]:
# use joblib.dump to persist the model to a file
from sklearn.externals import joblib
joblib.dump(logreg,'regresfilename.pk1')

C:\Users\sharv\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['regresfilename.pk1']

In [27]:
# use joblib.load to persist the model to a file
# create new estimator from the saved model
new_logreg_estimator = joblib.load('regresfilename.pk1')

In [28]:
# view the new estimator
new_logreg_estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
# validate and use new estimator to predict
new_logreg_estimator.predict(X_new) # output is same as X_new object predicted earlier.
# This proves that a model can b created, trained and persisted for future use.

array([0, 1])